version: '3.9'

services:
  api:
    hostname: api
    build: api/.
    expose: 
      - "8081"

  nginx:
    build: cors/.
    ports: 
      - "8888:80"
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - api